"""add timeframe to crypto_prices

Revision ID: 47cb76ce44f5
Revises: 94415a9b02e0
Create Date: 2025-09-27 15:38:42.297187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47cb76ce44f5'
down_revision: Union[str, None] = '94415a9b02e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
