"""create tables crypto_prices and coins

Revision ID: 51ca71371402
Revises: 
Create Date: 2025-09-28 09:42:40.405265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51ca71371402'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_currency', sa.String(), nullable=False),
    sa.Column('quote_currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol'),
    sa.UniqueConstraint('symbol', name='uix_symbol')
    )
    op.create_table('crypto_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin_id', sa.String(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('candle_type', sa.String(), nullable=False),
    sa.Column('upper_shadow', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('lower_shadow', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('volume', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coin_id', 'timestamp', 'timeframe', name='uix_coin_timestamp_timeframe')
    )
    op.create_index('idx_coin_timeframe', 'crypto_prices', ['coin_id', 'timeframe'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_coin_timeframe', table_name='crypto_prices')
    op.drop_table('crypto_prices')
    op.drop_table('coins')
    # ### end Alembic commands ###
