"""add not nullable to CryptoPrice

Revision ID: 62549ea20df4
Revises: fd7a349c1a28
Create Date: 2025-09-27 15:54:44.187167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62549ea20df4'
down_revision: Union[str, None] = 'fd7a349c1a28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crypto_prices', 'timeframe',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crypto_prices', 'timeframe',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
