"""create support_resistance_levels table

Revision ID: 6af8de90d6c1
Revises: 4dde357d19df
Create Date: 2025-10-08 11:40:08.555322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6af8de90d6c1'
down_revision: Union[str, None] = '4dde357d19df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_resistance_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('level_type', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'level_type', 'calculated_at', name='uix_sr_level')
    )
    op.create_index('idx_symbol_timeframe', 'support_resistance_levels', ['symbol', 'timeframe'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_symbol_timeframe', table_name='support_resistance_levels')
    op.drop_table('support_resistance_levels')
    # ### end Alembic commands ###
