"""remove uniq condition in SupportResistanceLevel

Revision ID: 97dadbd421be
Revises: d2084631a50e
Create Date: 2025-10-08 13:10:57.119203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97dadbd421be'
down_revision: Union[str, None] = 'd2084631a50e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_symbol_timeframe', table_name='support_resistance_levels')
    op.drop_constraint('uix_sr_level', 'support_resistance_levels', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_sr_level', 'support_resistance_levels', ['symbol', 'timeframe', 'level_type', 'calculated_at'])
    op.create_index('idx_symbol_timeframe', 'support_resistance_levels', ['symbol', 'timeframe'], unique=False)
    # ### end Alembic commands ###
