"""add volume to crypto_prices

Revision ID: ce3fc4734590
Revises: a3b8b232eeb1
Create Date: 2025-09-11 12:09:55.710224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce3fc4734590'
down_revision: Union[str, None] = 'a3b8b232eeb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crypto_prices', sa.Column('volume', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crypto_prices', 'volume')
    # ### end Alembic commands ###
