"""add coins table

Revision ID: fd7a349c1a28
Revises: 47cb76ce44f5
Create Date: 2025-09-27 15:53:21.687547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd7a349c1a28'
down_revision: Union[str, None] = '47cb76ce44f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crypto_prices', sa.Column('timeframe', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crypto_prices', 'timeframe')
    # ### end Alembic commands ###
